---
version: '2'
services:
  #consumer will consume until 2 minutes transpires without data
  kafka-consumer:
    image: confluentinc/cp-kafka:5.3.0
    volumes:
      - ./config:/config
      - interceptors:/interceptors/
    environment:
      CLASSPATH: '/interceptors/monitoring-interceptors-5.2.2.jar'
    command: "bash -c ' /config/perf-consumer.sh --topic location \
                                                --group $STAS_GROUP \
                                                --broker-list broker:9092 \
                                                --show-detailed-stats \
                                                --messages 2147483647 \
                                                --timeout 120000'"
